# Generated by Django 2.2 on 2021-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0002_auto_20210923_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='expense',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
